schema_version: 1

context:
  name: nvidia-tao-pytorch
  version: "7.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA-TAO/tao-pytorch/archive/refs/tags/${{ version }}.tar.gz
  sha256: 49094855daa44ba2ba4e8112d782c00d6838035a6c1ae2451158cb85e95f8755

build:
  number: 0
  script:
    env:
      TORCH_CUDA_ARCH_LIST: ${{ "7.5 8.0 8.6 8.9 9.0 10.0 12.0+PTX" if match(cuda_compiler_version, ">=13") else "7.0 7.5 8.0 8.6 8.9 9.0 10.0 12.0+PTX" }}
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip:
    - cuda_compiler_version == "None" or not linux or match(python, "<3.12")
  string: cuda_${{ cuda_compiler_version | version_to_buildstring }}py${{ python | version_to_buildstring }}h${{ hash }}_${{ build_number }}
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - ${{ stdlib('c') }}
    - libcublas-dev
    - libcusparse-dev
    - libcusolver-dev
  host:
    - pip
    - python
    - pytorch * cuda*
    - setuptools
  run:
    - python
    - pytorch * cuda*

tests:
  - python:
      imports:
        - nvidia_tao_pytorch.core
        - nvidia_tao_pytorch.cv
        - nvidia_tao_pytorch.multimodal
        - nvidia_tao_pytorch.pointcloud
        - nvidia_tao_pytorch.pruning
        - nvidia_tao_pytorch.sdg
        - nvidia_tao_pytorch.ssl
      pip_check: true

about:
  homepage: https://github.com/NVIDIA-TAO/tao-pytorch
  summary: TAO Toolkit deep learning networks with PyTorch backend
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
